# Generated by Django 4.2 on 2023-05-14 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update_dt')),
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='blog_id')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog_photo')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='category_id')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='simple one-line text.', max_length=100, verbose_name='DESCRIPTION')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update_dt')),
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='post_id')),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(null=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.blog')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='tag_id')),
                ('name', models.CharField(max_length=50)),
                ('posts', models.ManyToManyField(blank=True, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update_dt')),
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='comment_id')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
